kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # admin organiser backend
      - containerPort: 30100
        hostPort: 3000
      # admin organiser frontend
      - containerPort: 30200
        hostPort: 8080
      # guest backend
      - containerPort: 30300
        hostPort: 5173
      # guest frontend
      - containerPort: 30400
        hostPort: 8000
      # authenticator api
      - containerPort: 30500
        hostPort: 5000
      # rabbitmq service
      - containerPort: 30600
        hostPort: 15672
  - role: worker
