packages:
  - packages/*
  - apps/admin_organiser/ff_admin_organiser_backend
  - apps/admin_organiser/ff_admin_organiser_frontend
  - apps/guest/ff_guest_backend
  - apps/guest/ff_guest_frontend
  - apps/ff_authenticator_api
  - apps/ff_synchronizer_api