apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: queue-up
  name: guest-frontend-allow-host
  labels:
    app: guest-frontend
    component: policy
    policy-type: both
spec:
  podSelector:
    matchLabels:
      app: guest-frontend
      component: frontend
  ingress:
    # beware that this cidr should be machine specific in a prod setting
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
  egress:
    # beware that this cidr should be machine specific in a prod setting
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: guest-frontend-frontend-exposer
  labels:
    app: guest-frontend
    component: exposer
    exposer-source: frontend
    exposer-target: host
spec:
  type: NodePort
  selector:
    app: guest-frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30400

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: guest-frontend-frontend
  labels:
    app: guest-frontend
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest-frontend
      component: frontend
  template:
    metadata:
      labels:
        app: guest-frontend
        component: frontend
    spec:
      containers:
        - name: guest-frontend
          image: qu-guest-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

