# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: queue-up
#   name: guest-backend-allow-db-and-host
#   labels:
#     app: guest-backend
#     component: policy
#     policy-type: both
# spec:
#   podSelector:
#     matchLabels:
#       app: guest-backend
#       component: backend
#   ingress:
#     # beware that this cidr should be machine specific in a prod setting
#     - from:
#       - ipBlock:
#           cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 27017
#         - protocol: TCP
#           port: 3000
#         - protocol: TCP
#           port: 5672
#   egress:
#     # beware that this cidr should be machine specific in a prod setting
#     - to:
#       - ipBlock:
#           cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 27017
#         - protocol: TCP
#           port: 3000
#         - protocol: TCP
#           port: 5672

                   

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: guest-backend-backend-exposer
  labels:
    app: guest-backend
    component: exposer
    exposer-source: backend
    exposer-target: message-broker
spec:
  type: ClusterIP
  selector:
    app: guest-backend
    component: backend
  ports:
    - protocol: TCP
      port: 5672
      targetPort: mb-port

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: guest-backend-backend-exposer
  labels:
    app: guest-backend
    component: exposer
    exposer-source: backend
    exposer-target: host
spec:
  type: NodePort
  selector:
    app: guest-backend
    component: backend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: hono-port
      nodePort: 30300

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: guest-backend-backend
  labels:
    app: guest-backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest-backend
      component: backend
  template:
    metadata:
      labels:
        app: guest-backend
        component: backend
    spec:
      containers:
        - name: guest-backend
          image: qu-guest-backend:latest
          imagePullPolicy: Never
          ports:
            - name: hono-port
              containerPort: 3000
            - name: mb-port
              containerPort: 5672
