# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: queue-up
#   name: guest-synchronizer-allow-db
#   labels:
#     app: guest-synchronizer
#     component: policy
#     policy-type: both
# spec:
#   podSelector:
#     matchLabels:
#       app: guest-synchronizer
#       component: api
#   ingress:
#     - from:
#       - ipBlock:
#           cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 27017
#   egress:
#     - to:
#       - ipBlock:
#           cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 27017

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: guest-synchronizer-api-exposer
  labels:
    app: guest-synchronizer
    component: exposer
    exposer-source: api
    exposer-target: cluster
spec:
  type: ClusterIP
  selector:
    app: qu-guest-synchronizer-api-deployment
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: guest-synchronizer-api
  labels:
    app: guest-synchronizer
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest-synchronizer
      component: api
  template:
    metadata:
      labels:
        app: guest-synchronizer
        component: api
    spec:
      containers:
        - name: guest-synchronizer-api
          image: qu-guest-synchronizer-api:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000