apiVersion: v1
kind: Namespace
metadata:
  name: qu-guest-synchronizer-api

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qu-guest-allow-db
  namespace: qu-guest-synchronizer-api
spec:
  podSelector:
    matchLabels:
      app: qu-guest-synchronizer-deployment
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-guest-db
      ports:
        - protocol: TCP
          port: 27017
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-guest-db
      ports:
        - protocol: TCP
          port: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: qu-guest-synchronizer-api-service
  namespace: qu-guest-synchronizer-api
spec:
  type: ClusterIP
  selector:
    app: qu-guest-synchronizer-api-deployment
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-guest-synchronizer-api-deployment
  namespace: qu-guest-synchronizer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-guest-synchronizer-api
  template:
    metadata:
      labels:
        app: qu-guest-synchronizer-api
    spec:
      containers:
        - name: guest-synchronizer-api
          image: qu-guest-synchronizer-api:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000