apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-backend
  template:
    metadata:
      labels:
        app: qu-admin-organiser-backend
    spec:
      containers:
        - name: admin-organiser-backend
          image: qu-admin-organiser-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              hostPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-frontend
  template:
    metadata:
      labels:
        app: qu-admin-organiser-frontend
    spec:
      containers:
        - name: admin-organiser-frontend
          image: qu-admin-organiser-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-db
  template:
    metadata:
      labels:
        app: qu-admin-organiser-db
    spec:
      containers:
        - name: admin-organiser-db
          image: mysql:8
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_USER
              value: 'queue-up'
            - name: MYSQL_ROOT_PASSWORD
              value: 'queue-up'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-synchronizer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-synchronizer-api
  template:
    metadata:
      labels:
        app: qu-admin-organiser-synchronizer-api
    spec:
      containers:
        - name: admin-organiser-synchronizer-api
          image: qu-admin-organiser-synchronizer:latest
          ports:
          - containerPort: 3306
