apiVersion: v1
kind: Namespace
metadata:
  name: qu-authenticator

---

apiVersion: v1
kind: Service
metadata:
  name: qu-authenticator-db-service
  namespace: qu-authenticator
spec:
  clusterIP: None
  selector:
    app: qu-authenticator-db-service

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qu-authenticator-db-stateful-set
  namespace: qu-authenticator
spec:
  serviceName: qu-authenticator-db-service
  replicas: 3
  selector:
    matchLabels:
      app: qu-authenticator-db-stateful-set
  template:
    metadata:
      labels:
        app: qu-authenticator-db-stateful-set
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0
        command:
          - "mongod"
          - "--replSet"
          - "rs1"
          - "--bind_ip_all"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: qu-authenticator-db-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: qu-authenticator-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-authenticator-api-deployment
  namespace: qu-authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-authenticator-api-deployment
  template:
    metadata:
      labels:
        app: qu-authenticator-api-deployment
    spec:
      containers:
        - name: authenticator-api
          image: qu-authenticator-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: qu-authenticator-api-service
  namespace: qu-authenticator
spec:
  selector:
    app: qu-authenticator-api-deployment  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 5000      # The port exposed inside the cluster
      targetPort: 3000  # The container's port (update as needed)
      nodePort: 30500  # Static port on the node (choose any available port)
  type: NodePort  # Exposes the service on a port accessible outside the cluster
