apiVersion: v1
kind: Namespace
metadata:
  name: qu-authenticator

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qu-authenticator-allow-db-host
  namespace: qu-admin-organiser-backend
spec:
  podSelector:
    matchLabels:
      app: qu-authenticator-api-deployment
  ingress:
    # beware that this cidr should be machine specific in a prod setting
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # beware that this cidr should be machine specific in a prod setting
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-authenticator-api-deployment
  namespace: qu-authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-authenticator-api-deployment
  template:
    metadata:
      labels:
        app: qu-authenticator-api-deployment
    spec:
      containers:
        - name: authenticator-api
          image: qu-authenticator-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: qu-authenticator-api-service
  namespace: qu-authenticator
spec:
  selector:
    app: qu-authenticator-api-deployment  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 5000      # The port exposed inside the cluster
      targetPort: 3000  # The container's port (update as needed)
      nodePort: 30500  # Static port on the node (choose any available port)
  type: NodePort  # Exposes the service on a port accessible outside the cluster
