apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-authenticator-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-guest-db
  template:
    metadata:
      labels:
        app: qu-guest-db
    spec:
      containers:
        - name: guest-db
          image: mongo:8
          ports:
          - containerPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-authenticator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-authenticator-api
  template:
    metadata:
      labels:
        app: qu-authenticator-api
    spec:
      containers:
        - name: authenticator-api
          image: qu-authenticator-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              hostPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: qu-authenticator-api
spec:
  selector:
    app: qu-admin-organiser-backend  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 5000      # The port exposed inside the cluster
      targetPort: 3000  # The container's port (update as needed)
      nodePort: 30500  # Static port on the node (choose any available port)
  type: NodePort  # Exposes the service on a port accessible outside the cluster
