apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: queue-up
  name: authenticator-allow-host
  labels:
    app: authenticator
    component: policy
    policy-type: both
spec:
  podSelector:
    matchLabels:
      app: authenticator
      component: api
  ingress:
    # beware that this cidr should be machine specific in a prod setting
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # beware that this cidr should be machine specific in a prod setting
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: authenticator-api
  labels:
    app: authenticator
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticator
      component: api
  template:
    metadata:
      labels:
        app: authenticator
        component: api
    spec:
      containers:
        - name: authenticator-api
          image: qu-authenticator-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: authenticator-api-exposer
  labels:
    app: authenticator
    component: exposer
    exposer-source: api
    exposer-target: host
spec:
  type: NodePort
  selector:
    app: authenticator
    component: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 30500
