apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-guest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-guest-backend
  template:
    metadata:
      labels:
        app: qu-guest-backend
    spec:
      containers:
        - name: guest-backend
          image: qu-guest-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              hostPort: 5173

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-guest-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-guest-frontend
  template:
    metadata:
      labels:
        app: qu-guest-frontend
    spec:
      containers:
        - name: guest-frontend
          image: qu-guest-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-guest-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-guest-db
  template:
    metadata:
      labels:
        app: qu-guest-db
    spec:
      containers:
        - name: guest-db
          image: mongo:8
          ports:
          - containerPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-guest-synchronizer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-guest-synchronizer-api
  template:
    metadata:
      labels:
        app: qu-guest-synchronizer-api
    spec:
      containers:
        - name: guest-synchronizer-api
          image: qu-admin-organiser-synchronizer:latest
          ports:
          - containerPort: 3306
