apiVersion: v1
kind: Namespace
metadata:
  name: qu-message-broker

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-synchronizers
  namespace: qu-message-broker
spec:
  podSelector:
    matchLabels:
      app: qu-rabbitmq-deployment
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-admin-organiser-synchronizer
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-guest-synchronizer
      ports:
        - protocol: TCP
          port: 5672
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-admin-organiser-synchronizer
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-guest-synchronizer
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-rabbitmq-deployment
  namespace: qu-message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-message-broker-deployment
  template:
    metadata:
      labels:
        app: qu-message-broker-deployment
    spec:
      containers:
        - name: message-broker
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  name: qu-message-broker-service
  namespace: qu-message-broker
spec:
  type: ClusterIP
  selector:
    app: qu-message-broker-deployment
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: qu-message-broker-management-service
  namespace: qu-message-broker
spec:
  type: NodePort
  selector:
    app: qu-message-broker-deployment
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30600
