# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: queue-up
#   name: message-broker-allow-synchronizers
#   labels:
#     app: message-broker
#     component: policy
#     policy-type: both
# spec:
#   podSelector:
#     matchLabels:
#       app: message-broker
#       component: message-broker
#   ingress:
#     - from:
#         - podSelector:
#             matchLabels:
#               app: admin-organiser-backend
#               component: backend
#         - namespaceSelector:
#             matchLabels:
#               app: guest-backend
#               component: backend
#       ports:
#         - protocol: TCP
#           port: 5672
#         - protocol: TCP
#           port: 15672
#   egress:
#     - to:
#       - namespaceSelector:
#           matchLabels:
#             app: admin-organiser-synchronizer
#             component: api
#       - namespaceSelector:
#           matchLabels:
#             app: guest-synchronizer
#             component: api
#       ports:
#         - protocol: TCP
#           port: 5672
#         - protocol: TCP
#           port: 15672

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: message-broker-message-broker
  labels:
    app: message-broker
    component: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
      component: message-broker
  template:
    metadata:
      labels:
        app: message-broker
        component: message-broker
    spec:
      containers:
        - name: message-broker
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: message-broker-exposer
  labels:
    app: message-broker
    component: exposer
    exposer-source: message-broker
    exposer-target: cluster
spec:
  type: ClusterIP
  selector:
    app: message-broker
    component: message-broker
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: message-broker-management-exposer
  labels:
    app: message-broker
    component: exposer
    exposer-source: message-broker-management
    exposer-target: host
spec:
  type: NodePort
  selector:
    app: message-broker
    component: message-broker
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30600
