apiVersion: v1
kind: Namespace
metadata:
  name: qu-message-broker

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-synchronizers
  namespace: qu-message-broker
spec:
  podSelector:
    matchLabels:
      app: qu-rabbitmq
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-admin-organiser-synchronizer
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-guest-synchronizer
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-admin-organiser-synchronizer
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-guest-synchronizer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-rabbitmq
  namespace: qu-message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-message-broker-deployment
  template:
    metadata:
      labels:
        app: qu-message-broker-deployment
    spec:
      containers:
        - name: message-broker
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  name: qu-message-broker-service
  namespace: qu-message-broker
spec:
  type: ClusterIP
  selector:
    app: qu-message-broker-deployment
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672

---

# expose management to host
apiVersion: v1
kind: Service
metadata:
  name: qu-message-broker-management-service
  namespace: qu-message-broker
spec:
  type: NodePort  # Exposes the service on a port accessible outside the cluster
  selector:
    app: qu-message-broker-deployment  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 15672      # The port exposed inside the cluster
      targetPort: 15672  # The container's port (update as needed)
      nodePort: 30600  # Static port on the node (choose any available port)
