apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-rabbitmq
  template:
    metadata:
      labels:
        app: qu-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 15672
              hostPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  name: qu-rabbitmq
spec:
  selector:
    app: qu-rabbitmq  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 15672      # The port exposed inside the cluster
      targetPort: 15672  # The container's port (update as needed)
      nodePort: 30600  # Static port on the node (choose any available port)
  type: NodePort  # Exposes the service on a port accessible outside the cluster
