apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: qu-secrets-manager
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: "cce56ff0-493f-4c7f-af94-b2b6014143db"
  secretName: sm-secret
  map:
    - bwSecretId: c87a02e4-d599-4a1e-8a44-b2b601441a4d
      secretKeyName: sm-registry-token
  authToken:
    secretName: bw-auth-token
    secretKey: token