apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-rabbitmq
  template:
    metadata:
      labels:
        app: qu-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              hostPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-authenticator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-authenticator-api
  template:
    metadata:
      labels:
        app: qu-authenticator-api
    spec:
      containers:
        - name: authenticator-api
          image: qu-authenticator-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8080

