apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: queue-up
  name: admin-organiser-synchronizer-allow-message-broker
  labels:
    app: admin-organiser-synchronizer
    component: policy
    policy-type: both
spec:
  podSelector:
    matchLabels:
      app: admin-organiser-synchronizer
      component: api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: message-broker
              component: message-broker
      ports:
        - protocol: TCP
          port: 5672
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: message-broker
            component: message-broker
      ports:
        - protocol: TCP
          port: 5672

---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: admin-organiser-synchronizer-api-exposer
  labels:
    app: admin-organiser-synchronizer
    component: exposer
    exposer-source: api
    exposer-target: cluster
spec:
  type: ClusterIP
  selector:
    app: admin-organiser-synchronizer
    component: api
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: admin-organiser-synchronizer-api
  labels:
    app: admin-organiser-synchronizer
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-organiser-synchronizer
      component: api
  template:
    metadata:
      labels:
        app: admin-organiser-synchronizer
        component: api
    spec:
      containers:
        - name: admin-organiser-synchronizer-api
          image: qu-admin-organiser-synchronizer-api:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
