apiVersion: v1
kind: Namespace
metadata:
  name: qu-admin-organiser-db

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qu-admin-organiser-allow-backend-synchronizer
  namespace: qu-admin-organiser-db
spec:
  podSelector:
    matchLabels:
      app: qu-admin-organiser-db-deployment
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-admin-organiser-backend
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-admin-organiser-synchronizer
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-admin-organiser-backend
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-admin-organiser-synchronizer

---

apiVersion: v1
kind: Service
metadata:
  name: qu-admin-organiser-db-service
  namespace: qu-admin-organiser-db
spec:
  type: ClusterIP
  selector:
    app: qu-admin-organiser-db-deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-db-deployment
  namespace: qu-admin-organiser-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-db-deployment
  template:
    metadata:
      labels:
        app: qu-admin-organiser-db-deployment
    spec:
      containers:
        - name: admin-organiser-db
          image: mysql:8
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_USER
              value: 'queue-up'
            - name: MYSQL_ROOT_PASSWORD
              value: 'queue-up'

