apiVersion: v1
kind: Namespace
metadata:
  name: qu-admin-organiser-backend

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qu-admin-organiser-allow-db-host
  namespace: qu-admin-organiser-backend
spec:
  podSelector:
    matchLabels:
      app: qu-admin-organiser-backend-deployment
  ingress:
    # beware that this cidr should be machine specific in a prod setting
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5672
  egress:
    # beware that this cidr should be machine specific in a prod setting
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5672


---

apiVersion: v1
kind: Service
metadata:
  name: qu-admin-organiser-backend-service
  namespace: qu-admin-organiser-backend
spec:
  type: NodePort
  selector:
    app: qu-admin-organiser-backend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-backend-deployment
  namespace: qu-admin-organiser-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-backend-deployment
  template:
    metadata:
      labels:
        app: qu-admin-organiser-backend-deployment
    spec:
      containers:
        - name: admin-organiser-backend
          image: qu-admin-organiser-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

