apiVersion: v1
kind: Namespace
metadata:
  name: qu-admin-organiser-synchronizer-api

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qu-synchronizer-allow-db-message-broker
  namespace: qu-admin-organiser-synchronizer-api
spec:
  podSelector:
    matchLabels:
      app: qu-admin-organiser-synchronizer-api-deployment
  ingress:
    # beware that this cidr should be machine specific in a prod setting
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: qu-admin-organiser-message-broker
      ports:
        - protocol: TCP
          port: 5173
        - protocol: TCP
          port: 5672
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: qu-admin-organiser-message-broker
      ports:
        - protocol: TCP
          port: 5173
        - protocol: TCP
          port: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: qu-admin-organiser-synchronizer-api-service
  namespace: qu-admin-organiser-synchronizer-api
spec:
  type: ClusterIP
  selector:
    app: qu-admin-organiser-synchronizer-api-deployment
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-synchronizer-api-deployment
  namespace: qu-admin-organiser-synchronizer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-synchronizer-api-deployment
  template:
    metadata:
      labels:
        app: qu-admin-organiser-synchronizer-api-deployment
    spec:
      containers:
        - name: admin-organiser-synchronizer-api
          image: qu-admin-organiser-synchronizer-api:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
