apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: queue-up
  name: admin-organiser-backend-allow-host-and-message-broker
  labels:
    app: admin-organiser-backend
    component: policy
    policy-type: both
spec:
  podSelector:
    matchLabels:
      app: admin-organiser-backend
      component: backend
  ingress:
    # beware that this cidr should be machine specific in a prod setting
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5672
  egress:
    # beware that this cidr should be machine specific in a prod setting
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5672


---

apiVersion: v1
kind: Service
metadata:
  namespace: queue-up
  name: admin-organiser-backend-backend-exposer
  labels:
    app: admin-organiser-backend
    component: exposer
    exposer-source: backend
    exposer-target: host
spec:
  type: NodePort
  selector:
    app: admin-organiser-backend
    component: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue-up
  name: admin-organiser-backend-backend
  labels:
    app: admin-organiser-backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-organiser-backend
      component: backend
  template:
    metadata:
      labels:
        app: admin-organiser-backend
        component: backend
    spec:
      containers:
        - name: admin-organiser-backend
          image: qu-admin-organiser-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: secrets-manager
          env:
            - name: QUEUE_UP_REG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets-manager
                  key: registry-token

