apiVersion: apps/v1
kind: Deployment
metadata:
  name: qu-admin-organiser-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qu-admin-organiser-frontend
  template:
    metadata:
      labels:
        app: qu-admin-organiser-frontend
    spec:
      containers:
        - name: admin-organiser-frontend
          image: qu-admin-organiser-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: qu-admin-organiser-frontend
spec:
  selector:
    app: qu-admin-organiser-frontend  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 8080      # The port exposed inside the cluster
      targetPort: 80 # The container's port (update as needed)
      nodePort: 30200  # Static port on the node (choose any available port)
  type: NodePort  # Exposes the service on a port accessible outside the cluster