name: Push admin organiser backend image to github container registry

on:
  push:
    branches:
      - BOIS-43/*
    #paths:
    #  - apps/admin_organiser/qu_admin_organiser_backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      QUEUE_UP_REG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: ghcr.io/coderbois-2-0/dls_queue-up/qu_admin_organiser_backend
      PUSH: true
      TAG: 1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker buildx bake $IMAGE_NAME --no-cache

      - name: Push image
        run: docker push $IMAGE_NAME:$TAG
