name: Push base node image to github container registry

on:
  push:
    branches:
      - BOIS-43/*
    paths:
      - Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      PUSH: true
      TAG: 1.0.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker buildx bake qu_node

      - name: Push image
        run: docker push ghcr.io/coderbois-2-0/dls_queue-up/qu-node:$TAG
